version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
    networks:
      - elastic
    environment:
      - node.name=${node_name}
      - cluster.name=${cluster_name}
      - bootstrap.memory_lock=${bootstrap_memory_lock}
      - cluster.initial_master_nodes=${cluster_initial_master_nodes}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
    depends_on:
      - fluentd
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
    networks:
      - elastic
  
  nginx:
    image: nginx:alpine
    ports:
      - "20000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - voting
      - fluentd
    networks:
      - elastic
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx


  voting:
    build: .
    ports:
      - "9000:9000"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_CONNECTION=${SESSION_CONNECTION}
      - CACHE_DRIVER=${CACHE_DRIVER}
    depends_on:
      - fluentd
      - mysql
      - redis
    networks:
      - elastic
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: voting

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_AUTHENTICATION_PLUGIN=${MYSQL_AUTHENTICATION_PLUGIN}
    command: ['--default-authentication-plugin=mysql_native_password']
    depends_on:
      - fluentd
    networks:
      - elastic
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: mysql

  redis:
    image: redis:alpine
    networks:
      - elastic
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: redis

networks:
  elastic:
